language: go

env:
    - GO111MODULE=on

before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

script:
    - go build ./...
    - go test -cover ./...
    - golangci-lint run --deadline 20m --enable-all
