language: go

before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

script:
    - cd moviecontrol && go build
    - cd moviecontrol && go test -v -race
    - golangci-lint run --deadline 20m --enable-all
