language: go

env:
    - GO111MODULE=on

before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

script:
    - go build ./...
    - go test -cover ./moviecontrol/moviecontrol.go ./moviecontrol/moviecontrol_test.go
    - go test -cover ./roomcontrol/roomcontrol.go ./roomcontrol/roomcontrol_test.go
    - go test -cover ./showcontrol/showcontrol.go ./showcontrol/showcontrol_test.go
    - golangci-lint run --deadline 20m --enable-all
