// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movieconfig.proto

package movieconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMovieRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMovieRequest) Reset()         { *m = AddMovieRequest{} }
func (m *AddMovieRequest) String() string { return proto.CompactTextString(m) }
func (*AddMovieRequest) ProtoMessage()    {}
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{0}
}

func (m *AddMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMovieRequest.Unmarshal(m, b)
}
func (m *AddMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMovieRequest.Marshal(b, m, deterministic)
}
func (m *AddMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMovieRequest.Merge(m, src)
}
func (m *AddMovieRequest) XXX_Size() int {
	return xxx_messageInfo_AddMovieRequest.Size(m)
}
func (m *AddMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMovieRequest proto.InternalMessageInfo

func (m *AddMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type RequestResponse struct {
	Succeeded            bool     `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{1}
}

func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (m *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(m, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *RequestResponse) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type DeleteMovieRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{2}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMovieRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieRequest) Reset()         { *m = GetMovieRequest{} }
func (m *GetMovieRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieRequest) ProtoMessage()    {}
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{3}
}

func (m *GetMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieRequest.Unmarshal(m, b)
}
func (m *GetMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieRequest.Marshal(b, m, deterministic)
}
func (m *GetMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieRequest.Merge(m, src)
}
func (m *GetMovieRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieRequest.Size(m)
}
func (m *GetMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieRequest proto.InternalMessageInfo

type MovieData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{4}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MovieData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetMovieResponse struct {
	Data                 []*MovieData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMovieResponse) Reset()         { *m = GetMovieResponse{} }
func (m *GetMovieResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieResponse) ProtoMessage()    {}
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c37380506849bd, []int{5}
}

func (m *GetMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieResponse.Unmarshal(m, b)
}
func (m *GetMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieResponse.Marshal(b, m, deterministic)
}
func (m *GetMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieResponse.Merge(m, src)
}
func (m *GetMovieResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieResponse.Size(m)
}
func (m *GetMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieResponse proto.InternalMessageInfo

func (m *GetMovieResponse) GetData() []*MovieData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AddMovieRequest)(nil), "AddMovieRequest")
	proto.RegisterType((*RequestResponse)(nil), "RequestResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "DeleteMovieRequest")
	proto.RegisterType((*GetMovieRequest)(nil), "GetMovieRequest")
	proto.RegisterType((*MovieData)(nil), "MovieData")
	proto.RegisterType((*GetMovieResponse)(nil), "GetMovieResponse")
}

func init() { proto.RegisterFile("movieconfig.proto", fileDescriptor_c5c37380506849bd) }

var fileDescriptor_c5c37380506849bd = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x6c, 0xf2, 0x5e, 0x51, 0xb2, 0x45, 0x24, 0x31, 0x1c, 0xa2, 0x0a, 0xa1, 0xca, 0x42, 0xa2,
	0x27, 0x8b, 0x06, 0x89, 0x3b, 0xa2, 0x88, 0x13, 0x17, 0xff, 0x81, 0x89, 0x17, 0x64, 0x29, 0xc4,
	0xa5, 0xde, 0xf0, 0x53, 0xfc, 0x24, 0xaa, 0xd3, 0x92, 0x60, 0x38, 0xce, 0x68, 0x3c, 0x9e, 0x99,
	0x85, 0xe2, 0xcd, 0x7e, 0x18, 0xac, 0x6d, 0xfb, 0x62, 0x5e, 0xc5, 0x66, 0x6b, 0xc9, 0xf2, 0x2b,
	0xc8, 0xee, 0xb4, 0x7e, 0xda, 0xf1, 0x12, 0xdf, 0x3b, 0x74, 0xc4, 0xce, 0x60, 0x4a, 0x86, 0x1a,
	0x2c, 0xa3, 0x45, 0xb4, 0x4c, 0x65, 0x0f, 0xf8, 0x03, 0x64, 0x7b, 0x81, 0x44, 0xb7, 0xb1, 0xad,
	0x43, 0x76, 0x0e, 0xa9, 0xeb, 0xea, 0x1a, 0x51, 0xa3, 0xf6, 0xe2, 0x44, 0x0e, 0xc4, 0xce, 0xa6,
	0x56, 0x9d, 0xc3, 0x32, 0xee, 0x6d, 0x3c, 0xe0, 0x97, 0xc0, 0xd6, 0xd8, 0x20, 0xe1, 0x8f, 0x2f,
	0x4f, 0x20, 0x36, 0xbd, 0xc5, 0x54, 0xc6, 0x46, 0xf3, 0x02, 0xb2, 0x47, 0xa4, 0xb1, 0x84, 0xaf,
	0x20, 0xf5, 0x78, 0xad, 0x48, 0x85, 0xfa, 0x21, 0x72, 0x3c, 0x8e, 0x5c, 0x41, 0x3e, 0xb8, 0xec,
	0x33, 0x5f, 0xc0, 0x7f, 0xad, 0x48, 0x95, 0xd1, 0xe2, 0xdf, 0x72, 0x56, 0x81, 0xf8, 0xf6, 0x94,
	0x9e, 0xaf, 0x3e, 0x23, 0x38, 0xf6, 0xdc, 0xbd, 0x6d, 0x69, 0x6b, 0x1b, 0x76, 0x0d, 0xc9, 0x61,
	0x20, 0x96, 0x8b, 0x60, 0xab, 0x79, 0x2e, 0x82, 0x51, 0xf8, 0x84, 0xdd, 0xc2, 0x6c, 0x54, 0x91,
	0x9d, 0x8a, 0xdf, 0x85, 0xff, 0x7c, 0xb7, 0x82, 0xe4, 0x10, 0x97, 0xe5, 0x22, 0xe8, 0x3f, 0x2f,
	0x44, 0xd8, 0x85, 0x4f, 0x9e, 0x8f, 0xfc, 0x11, 0x6f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x77, 0x6c, 0xa9, 0xd9, 0x01, 0x00, 0x00,
}
