// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoconfig.proto

package protoconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type AddMovieRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMovieRequest) Reset()         { *m = AddMovieRequest{} }
func (m *AddMovieRequest) String() string { return proto.CompactTextString(m) }
func (*AddMovieRequest) ProtoMessage()    {}
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{2}
}

func (m *AddMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMovieRequest.Unmarshal(m, b)
}
func (m *AddMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMovieRequest.Marshal(b, m, deterministic)
}
func (m *AddMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMovieRequest.Merge(m, src)
}
func (m *AddMovieRequest) XXX_Size() int {
	return xxx_messageInfo_AddMovieRequest.Size(m)
}
func (m *AddMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMovieRequest proto.InternalMessageInfo

func (m *AddMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type RequestResponse struct {
	Succeeded            bool     `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{3}
}

func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (m *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(m, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

func (m *RequestResponse) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *RequestResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteMovieRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{4}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMovieRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieRequest) Reset()         { *m = GetMovieRequest{} }
func (m *GetMovieRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieRequest) ProtoMessage()    {}
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{5}
}

func (m *GetMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieRequest.Unmarshal(m, b)
}
func (m *GetMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieRequest.Marshal(b, m, deterministic)
}
func (m *GetMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieRequest.Merge(m, src)
}
func (m *GetMovieRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieRequest.Size(m)
}
func (m *GetMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieRequest proto.InternalMessageInfo

type MovieData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{6}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MovieData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetMovieResponse struct {
	Data                 []*MovieData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMovieResponse) Reset()         { *m = GetMovieResponse{} }
func (m *GetMovieResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieResponse) ProtoMessage()    {}
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{7}
}

func (m *GetMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieResponse.Unmarshal(m, b)
}
func (m *GetMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieResponse.Marshal(b, m, deterministic)
}
func (m *GetMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieResponse.Merge(m, src)
}
func (m *GetMovieResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieResponse.Size(m)
}
func (m *GetMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieResponse proto.InternalMessageInfo

func (m *GetMovieResponse) GetData() []*MovieData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddRoomRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	SeatsPerRow          int32    `protobuf:"varint,3,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoomRequest) Reset()         { *m = AddRoomRequest{} }
func (m *AddRoomRequest) String() string { return proto.CompactTextString(m) }
func (*AddRoomRequest) ProtoMessage()    {}
func (*AddRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{8}
}

func (m *AddRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoomRequest.Unmarshal(m, b)
}
func (m *AddRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoomRequest.Marshal(b, m, deterministic)
}
func (m *AddRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoomRequest.Merge(m, src)
}
func (m *AddRoomRequest) XXX_Size() int {
	return xxx_messageInfo_AddRoomRequest.Size(m)
}
func (m *AddRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoomRequest proto.InternalMessageInfo

func (m *AddRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRoomRequest) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *AddRoomRequest) GetSeatsPerRow() int32 {
	if m != nil {
		return m.SeatsPerRow
	}
	return 0
}

type DeleteRoomRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoomRequest) Reset()         { *m = DeleteRoomRequest{} }
func (m *DeleteRoomRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoomRequest) ProtoMessage()    {}
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{9}
}

func (m *DeleteRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoomRequest.Unmarshal(m, b)
}
func (m *DeleteRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoomRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoomRequest.Merge(m, src)
}
func (m *DeleteRoomRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoomRequest.Size(m)
}
func (m *DeleteRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoomRequest proto.InternalMessageInfo

func (m *DeleteRoomRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomRequest) Reset()         { *m = GetRoomRequest{} }
func (m *GetRoomRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoomRequest) ProtoMessage()    {}
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{10}
}

func (m *GetRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomRequest.Unmarshal(m, b)
}
func (m *GetRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomRequest.Marshal(b, m, deterministic)
}
func (m *GetRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomRequest.Merge(m, src)
}
func (m *GetRoomRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoomRequest.Size(m)
}
func (m *GetRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomRequest proto.InternalMessageInfo

type GetSingleRoomRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleRoomRequest) Reset()         { *m = GetSingleRoomRequest{} }
func (m *GetSingleRoomRequest) String() string { return proto.CompactTextString(m) }
func (*GetSingleRoomRequest) ProtoMessage()    {}
func (*GetSingleRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{11}
}

func (m *GetSingleRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleRoomRequest.Unmarshal(m, b)
}
func (m *GetSingleRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleRoomRequest.Marshal(b, m, deterministic)
}
func (m *GetSingleRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleRoomRequest.Merge(m, src)
}
func (m *GetSingleRoomRequest) XXX_Size() int {
	return xxx_messageInfo_GetSingleRoomRequest.Size(m)
}
func (m *GetSingleRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleRoomRequest proto.InternalMessageInfo

func (m *GetSingleRoomRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RoomData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	SeatsPerRow          int32    `protobuf:"varint,4,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{12}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomData) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *RoomData) GetSeatsPerRow() int32 {
	if m != nil {
		return m.SeatsPerRow
	}
	return 0
}

type GetRoomResponse struct {
	Data                 []*RoomData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRoomResponse) Reset()         { *m = GetRoomResponse{} }
func (m *GetRoomResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoomResponse) ProtoMessage()    {}
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{13}
}

func (m *GetRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomResponse.Unmarshal(m, b)
}
func (m *GetRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomResponse.Marshal(b, m, deterministic)
}
func (m *GetRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomResponse.Merge(m, src)
}
func (m *GetRoomResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoomResponse.Size(m)
}
func (m *GetRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomResponse proto.InternalMessageInfo

func (m *GetRoomResponse) GetData() []*RoomData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddShowRequest struct {
	MovieId              int32    `protobuf:"varint,1,opt,name=movieId,proto3" json:"movieId,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddShowRequest) Reset()         { *m = AddShowRequest{} }
func (m *AddShowRequest) String() string { return proto.CompactTextString(m) }
func (*AddShowRequest) ProtoMessage()    {}
func (*AddShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{14}
}

func (m *AddShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddShowRequest.Unmarshal(m, b)
}
func (m *AddShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddShowRequest.Marshal(b, m, deterministic)
}
func (m *AddShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddShowRequest.Merge(m, src)
}
func (m *AddShowRequest) XXX_Size() int {
	return xxx_messageInfo_AddShowRequest.Size(m)
}
func (m *AddShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddShowRequest proto.InternalMessageInfo

func (m *AddShowRequest) GetMovieId() int32 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *AddShowRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type DeleteShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowRequest) Reset()         { *m = DeleteShowRequest{} }
func (m *DeleteShowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowRequest) ProtoMessage()    {}
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{15}
}

func (m *DeleteShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowRequest.Unmarshal(m, b)
}
func (m *DeleteShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowRequest.Merge(m, src)
}
func (m *DeleteShowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowRequest.Size(m)
}
func (m *DeleteShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowRequest proto.InternalMessageInfo

func (m *DeleteShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AvailableSeatRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Row                  int32    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Seat                 int32    `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`
	Write                bool     `protobuf:"varint,4,opt,name=write,proto3" json:"write,omitempty"`
	Value                bool     `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvailableSeatRequest) Reset()         { *m = AvailableSeatRequest{} }
func (m *AvailableSeatRequest) String() string { return proto.CompactTextString(m) }
func (*AvailableSeatRequest) ProtoMessage()    {}
func (*AvailableSeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca36e7c14b0b8c5, []int{16}
}

func (m *AvailableSeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvailableSeatRequest.Unmarshal(m, b)
}
func (m *AvailableSeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvailableSeatRequest.Marshal(b, m, deterministic)
}
func (m *AvailableSeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvailableSeatRequest.Merge(m, src)
}
func (m *AvailableSeatRequest) XXX_Size() int {
	return xxx_messageInfo_AvailableSeatRequest.Size(m)
}
func (m *AvailableSeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvailableSeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvailableSeatRequest proto.InternalMessageInfo

func (m *AvailableSeatRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AvailableSeatRequest) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *AvailableSeatRequest) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *AvailableSeatRequest) GetWrite() bool {
	if m != nil {
		return m.Write
	}
	return false
}

func (m *AvailableSeatRequest) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*AddMovieRequest)(nil), "AddMovieRequest")
	proto.RegisterType((*RequestResponse)(nil), "RequestResponse")
	proto.RegisterType((*DeleteMovieRequest)(nil), "DeleteMovieRequest")
	proto.RegisterType((*GetMovieRequest)(nil), "GetMovieRequest")
	proto.RegisterType((*MovieData)(nil), "MovieData")
	proto.RegisterType((*GetMovieResponse)(nil), "GetMovieResponse")
	proto.RegisterType((*AddRoomRequest)(nil), "AddRoomRequest")
	proto.RegisterType((*DeleteRoomRequest)(nil), "DeleteRoomRequest")
	proto.RegisterType((*GetRoomRequest)(nil), "GetRoomRequest")
	proto.RegisterType((*GetSingleRoomRequest)(nil), "GetSingleRoomRequest")
	proto.RegisterType((*RoomData)(nil), "RoomData")
	proto.RegisterType((*GetRoomResponse)(nil), "GetRoomResponse")
	proto.RegisterType((*AddShowRequest)(nil), "AddShowRequest")
	proto.RegisterType((*DeleteShowRequest)(nil), "DeleteShowRequest")
	proto.RegisterType((*AvailableSeatRequest)(nil), "AvailableSeatRequest")
}

func init() { proto.RegisterFile("protoconfig.proto", fileDescriptor_6ca36e7c14b0b8c5) }

var fileDescriptor_6ca36e7c14b0b8c5 = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x93, 0xa6, 0x49, 0x26, 0x6d, 0xe2, 0xec, 0xd7, 0x7e, 0x8a, 0x2c, 0x40, 0xd1, 0x82,
	0x20, 0x12, 0xd2, 0xaa, 0x75, 0x50, 0xef, 0x4b, 0x2b, 0x85, 0x5e, 0x80, 0x90, 0x2b, 0x6e, 0xb8,
	0x73, 0xe3, 0x69, 0x6a, 0xe1, 0x78, 0x8b, 0xbd, 0x69, 0xe0, 0x39, 0x78, 0x0c, 0x5e, 0x88, 0xc7,
	0x41, 0xbb, 0xde, 0x8d, 0x7f, 0xea, 0x86, 0xbb, 0x9d, 0xc9, 0xcc, 0xec, 0x9c, 0xb3, 0xe7, 0x38,
	0x30, 0xba, 0x4f, 0xb8, 0xe0, 0x0b, 0x1e, 0xdf, 0x86, 0x4b, 0xa6, 0xce, 0x94, 0xc2, 0xc1, 0x07,
	0x8c, 0x22, 0xee, 0xe1, 0xf7, 0x35, 0xa6, 0x82, 0x10, 0xd8, 0x8b, 0xfd, 0x15, 0x8e, 0xad, 0x89,
	0x35, 0xed, 0x79, 0xea, 0x4c, 0xdf, 0xc2, 0xa1, 0xae, 0x49, 0xef, 0x79, 0x9c, 0x22, 0x71, 0xa0,
	0xbb, 0x4c, 0x10, 0x45, 0x18, 0x2f, 0xc7, 0x4d, 0x55, 0xb8, 0x8d, 0xe9, 0x1b, 0x18, 0x9e, 0x07,
	0xc1, 0x47, 0xfe, 0x10, 0xa2, 0x99, 0x79, 0x04, 0x6d, 0x11, 0x8a, 0xc8, 0x0c, 0xcd, 0x02, 0xfa,
	0x05, 0x86, 0xba, 0x60, 0x3b, 0xf7, 0x19, 0xf4, 0xd2, 0xf5, 0x62, 0x81, 0x18, 0x60, 0xa0, 0x8a,
	0xbb, 0x5e, 0x9e, 0x90, 0x63, 0x16, 0xfe, 0x3a, 0x45, 0x7d, 0x65, 0x16, 0x90, 0x01, 0x34, 0xc3,
	0x60, 0xdc, 0x9a, 0x58, 0xd3, 0xb6, 0xd7, 0x0c, 0x03, 0xfa, 0x0a, 0xc8, 0x25, 0x46, 0x28, 0xb0,
	0xb4, 0x42, 0x56, 0x65, 0x6d, 0xab, 0x46, 0x30, 0x9c, 0xa3, 0x28, 0x96, 0xd0, 0x53, 0xe8, 0xa9,
	0xf8, 0xd2, 0x17, 0x7e, 0xb5, 0x3e, 0x87, 0xd0, 0x2c, 0x42, 0x70, 0xc1, 0xce, 0xa7, 0x68, 0x0c,
	0x2f, 0x60, 0x2f, 0xf0, 0x85, 0x3f, 0xb6, 0x26, 0xad, 0x69, 0xdf, 0x05, 0xb6, 0x9d, 0xe9, 0xa9,
	0x3c, 0xfd, 0x0a, 0x83, 0xf3, 0x20, 0xf0, 0x38, 0x5f, 0xed, 0xa0, 0x5c, 0xe6, 0x12, 0xbe, 0x49,
	0xd5, 0x75, 0x6d, 0x4f, 0x9d, 0xc9, 0x04, 0xfa, 0x29, 0xfa, 0x22, 0xfd, 0x8c, 0x89, 0xc7, 0x37,
	0x1a, 0x72, 0x31, 0x45, 0x5f, 0xc2, 0x28, 0xc3, 0x5e, 0x1c, 0x5f, 0x85, 0x6e, 0xc3, 0x60, 0x8e,
	0xa2, 0x50, 0x41, 0x5f, 0xc3, 0xd1, 0x1c, 0xc5, 0x75, 0x18, 0x2f, 0xa3, 0x9d, 0x9d, 0x01, 0x74,
	0xe5, 0xcf, 0xb5, 0x04, 0x19, 0x10, 0xcd, 0x1a, 0x10, 0xad, 0xa7, 0x41, 0xec, 0x3d, 0x06, 0x71,
	0xa2, 0x9e, 0x26, 0xdb, 0x43, 0x73, 0xfa, 0xbc, 0xc4, 0x69, 0x8f, 0x99, 0x2d, 0x34, 0xa5, 0xef,
	0x15, 0xa5, 0xd7, 0x77, 0x7c, 0x63, 0x36, 0x1f, 0x43, 0x67, 0x25, 0x79, 0xbf, 0x32, 0x2b, 0x9a,
	0x90, 0xfc, 0x0f, 0xfb, 0x09, 0xe7, 0xab, 0xab, 0x40, 0x53, 0xab, 0xa3, 0x9c, 0xba, 0xe2, 0x98,
	0x2a, 0x01, 0x3f, 0xe0, 0xe8, 0xfc, 0xc1, 0x0f, 0x23, 0xff, 0x26, 0xc2, 0x6b, 0xf4, 0xc5, 0x13,
	0x75, 0xc4, 0x86, 0x56, 0xc2, 0x37, 0xfa, 0x06, 0x79, 0x94, 0x54, 0x48, 0x8c, 0x86, 0x0a, 0x79,
	0x96, 0x9a, 0xda, 0x24, 0xa1, 0x40, 0x45, 0x42, 0xd7, 0xcb, 0x02, 0x99, 0x7d, 0xf0, 0xa3, 0x35,
	0x8e, 0xdb, 0x59, 0x56, 0x05, 0xee, 0x0c, 0x3a, 0x73, 0xe9, 0x30, 0x4c, 0xc8, 0x14, 0xda, 0xca,
	0x8d, 0xe4, 0x90, 0x15, 0x9d, 0xeb, 0x0c, 0x58, 0xc9, 0xa4, 0xb4, 0xe1, 0xfe, 0xb6, 0xe0, 0x40,
	0xc9, 0xef, 0x82, 0xc7, 0x22, 0xe1, 0x11, 0x39, 0x81, 0xae, 0xf1, 0x26, 0xb1, 0x59, 0xc5, 0xa6,
	0x8e, 0xcd, 0x2a, 0x7e, 0xa4, 0x0d, 0x72, 0x06, 0xfd, 0x82, 0x9b, 0xc8, 0x7f, 0xec, 0xb1, 0xb7,
	0x6a, 0xfb, 0x4e, 0xa1, 0x6b, 0x9c, 0x41, 0x6c, 0x56, 0xb1, 0x9a, 0x33, 0x62, 0x55, 0xdb, 0xd0,
	0x86, 0xfb, 0xc7, 0x82, 0xbe, 0x7c, 0x58, 0xb3, 0x2c, 0x83, 0x8e, 0x36, 0x0a, 0x19, 0xb2, 0xb2,
	0x65, 0x6a, 0xaf, 0x7c, 0x07, 0x90, 0x8b, 0x9f, 0x10, 0xf6, 0xc8, 0x09, 0xb5, 0x5d, 0x0c, 0x3a,
	0x5a, 0x6d, 0x64, 0xc8, 0xca, 0xbe, 0x70, 0x6c, 0x56, 0x11, 0x22, 0x6d, 0x90, 0x19, 0x1c, 0x96,
	0xbc, 0x42, 0x8e, 0x59, 0x9d, 0x77, 0x9c, 0x5c, 0xa4, 0xb4, 0xe1, 0xfe, 0x6a, 0x42, 0x5f, 0xea,
	0xaa, 0x0c, 0x4d, 0x66, 0x32, 0x68, 0x05, 0xcd, 0xed, 0x86, 0xa6, 0x5a, 0x0c, 0xb4, 0x7f, 0x75,
	0x9d, 0x41, 0xef, 0xe2, 0x0e, 0x17, 0xdf, 0xa4, 0x52, 0xc9, 0x31, 0xab, 0x53, 0x6e, 0x6d, 0xdf,
	0x0c, 0x46, 0x9f, 0xb8, 0x08, 0x6f, 0x7f, 0x66, 0x9f, 0x2e, 0x75, 0x17, 0x29, 0x7c, 0xc8, 0x9e,
	0x78, 0x70, 0x3b, 0x6b, 0x52, 0xb0, 0xb3, 0x9e, 0x9c, 0x83, 0xba, 0x96, 0x9b, 0x7d, 0xf5, 0x0f,
	0x34, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x48, 0x5a, 0x90, 0xdb, 0x96, 0x06, 0x00, 0x00,
}
